### ISSUE TITLE
methods to read constants

### ISSUE THREAD

**Issue by vladiuz1** [LaunchX-Dev/launchx-smartcontracts#1]
address public lnx_address;
    address public lnxp_address;
    uint256 public lock_start;  // todo use uint40
    uint256 public lock_end;

![image](https://user-images.githubusercontent.com/22708849/123844920-47b09a80-d91c-11eb-937b-26bf6df25235.png)

After a bit of consideration, I figured we will need `view` methods to read these constants.

lets call them:

# getTokenAddress
Get the LNCHX token address

# getSyntheticTokenAddress
Get the LNCHXP token address

# getLockStartTime
Get the lock period starting time

# getLockEndTime
Get the lock period ending time

**Comment by vsmelov** [comment]
fixed
