### ISSUE TITLE
Likely error in this contract

### ISSUE THREAD

**Issue by vladiuz1** [LaunchX-Dev/launchx-smartcontracts#3]
https://github.com/LaunchX-Dev/launchx-smartcontracts/blob/1cd85256051146f1b9045137665fae722afc0390/Staking.sol#L119

This should actually return the total staked minus total withdrawn.

**Comment by vsmelov** [comment]
when withdrawal happens it decrease the balance of the contract so it will work correctly

**Comment by vsmelov** [comment]
fixed
